name: Ubuntu LTS Glibc Release x86

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: install ubuntu glibc dependencies
        run: sudo ./WIN/SVO/install_ubuntu_glibc_dependencies.sh x86
      - name: build ubuntu glibc release
        run: ./WIN/SVO/build.sh release x86
      - name: test ubuntu glibc release
        run: ./WIN/SVO/run.sh release x86