name: Ubuntu LTS Glibc Debug x64

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: install ubuntu glibc dependencies
        run: sudo ./WIN/SVO/install_ubuntu_glibc_dependencies.sh x64
      - name: build ubuntu glibc debug
        run: ./WIN/SVO/build.sh debug x64
      - name: test ubuntu glibc debug
        run: ./WIN/SVO/run.sh debug x64